import * as XLSX from 'xlsx';
import type { IncomeTransaction, IpProfile, TaxPeriodResult } from '../types';
import { formatMoney } from './format';

export interface DocumentDraftForm {
  customerName: string;
  customerInn: string;
  serviceName: string;
  amount: number;
  number: string;
  date: string;
}

export function exportIncomeReportXlsx(profile: IpProfile | null, incomes: IncomeTransaction[]): void {
  const rows = [
    ['Income report'],
    ['IP', profile?.ipFullName ?? ''],
    ['INN', profile?.inn ?? ''],
    [],
    ['Date', 'Counterparty', 'INN', 'Description', 'Amount', 'Status'],
    ...incomes.map((item) => [item.date, item.counterpartyName, item.counterpartyInn ?? '', item.description, item.amount, item.taxStatus]),
  ];
  writeBook('income-report.xlsx', 'Income', rows);
}

export function exportKudirXlsx(profile: IpProfile | null, incomes: IncomeTransaction[]): void {
  const taxable = incomes.filter((item) => item.taxStatus === 'taxable').sort((a, b) => a.date.localeCompare(b.date));
  const rows = [
    ['KUDIR draft'],
    ['IP', profile?.ipFullName ?? ''],
    ['INN', profile?.inn ?? ''],
    ['Tax system', 'USN income'],
    [],
    ['#', 'Date', 'Document', 'Operation content', 'Income'],
    ...taxable.map((item, index) => [index + 1, item.date, item.counterpartyName, item.description, item.amount]),
  ];
  writeBook('kudir-draft.xlsx', 'KUDIR', rows);
}

export function exportUsnDraftXlsx(profile: IpProfile | null, taxResults: TaxPeriodResult[]): void {
  const rows = [
    ['USN declaration draft'],
    ['IP', profile?.ipFullName ?? ''],
    ['INN', profile?.inn ?? ''],
    [],
    ['Period', 'Income', 'USN before deduction', 'Fixed contribution', 'Additional contribution', 'Deduction', 'Previous', 'Current amount', 'Due date'],
    ...taxResults.map((item) => [item.label, item.incomeTotal, item.usnBeforeDeduction, item.fixedContribution, item.additionalContribution, item.deductionApplied, item.previousAccruedTax, item.taxToPay, item.dueDate]),
  ];
  writeBook('usn-declaration-draft.xlsx', 'USN draft', rows);
}

export function printInvoice(profile: IpProfile | null, form: DocumentDraftForm): void {
  openPrintDocument(`Invoice ${form.number}`, buildCommercialDocument('Invoice', profile, form));
}

export function printAct(profile: IpProfile | null, form: DocumentDraftForm): void {
  openPrintDocument(`Act ${form.number}`, buildCommercialDocument('Act', profile, form));
}

function writeBook(fileName: string, sheetName: string, rows: unknown[][]): void {
  const workbook = XLSX.utils.book_new();
  const worksheet = XLSX.utils.aoa_to_sheet(rows);
  worksheet['!cols'] = [{ wch: 18 }, { wch: 34 }, { wch: 18 }, { wch: 42 }, { wch: 18 }, { wch: 18 }, { wch: 18 }, { wch: 18 }, { wch: 18 }];
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  XLSX.writeFile(workbook, fileName);
}

function buildCommercialDocument(title: string, profile: IpProfile | null, form: DocumentDraftForm): string {
  const seller = profile?.ipFullName || 'Individual entrepreneur';
  const sellerInn = profile?.inn || '';
  const customer = form.customerName || 'Customer';
  const amount = Number.isFinite(form.amount) ? form.amount : 0;
  return `
    <main class="doc">
      <header class="header">
        <div>
          <p class="muted">${escapeHtml(title)}</p>
          <h1>${escapeHtml(title)} #${escapeHtml(form.number || '1')}</h1>
        </div>
        <p>${escapeHtml(form.date)}</p>
      </header>
      <section class="grid">
        <div><strong>Seller</strong><p>${escapeHtml(seller)}</p><p>INN: ${escapeHtml(sellerInn)}</p></div>
        <div><strong>Customer</strong><p>${escapeHtml(customer)}</p><p>INN: ${escapeHtml(form.customerInn)}</p></div>
      </section>
      <table>
        <thead><tr><th>#</th><th>Service</th><th>Amount</th></tr></thead>
        <tbody><tr><td>1</td><td>${escapeHtml(form.serviceName || 'Service')}</td><td>${formatMoney(amount)}</td></tr></tbody>
        <tfoot><tr><td colspan="2">Total</td><td>${formatMoney(amount)}</td></tr></tfoot>
      </table>
      <section class="signatures">
        <div><p>Seller signature</p><span></span></div>
        <div><p>Customer signature</p><span></span></div>
      </section>
      <p class="note">Draft generated by Buh2 MVP. Check details before sending to a counterparty.</p>
    </main>`;
}

function openPrintDocument(title: string, body: string): void {
  const printWindow = window.open('', '_blank', 'width=960,height=900');
  if (!printWindow) return;
  printWindow.document.open();
  printWindow.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>${printStyles()}</style></head><body>${body}<script>window.onload=function(){window.print()}</script></body></html>`);
  printWindow.document.close();
}

function printStyles(): string {
  return `body{font-family:Arial,sans-serif;background:#f8fafc;color:#0f172a;margin:0;padding:40px}.doc{max-width:860px;margin:0 auto;background:white;padding:44px;border-radius:24px}.header{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid #e2e8f0;padding-bottom:24px;margin-bottom:28px}h1{font-size:36px;margin:6px 0 0}.muted,.note{color:#64748b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:28px}.grid>div{background:#f1f5f9;border-radius:16px;padding:18px}table{width:100%;border-collapse:collapse;margin:24px 0}th,td{border:1px solid #cbd5e1;padding:14px;text-align:left}tfoot td{font-weight:700}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:60px}.signatures span{display:block;border-bottom:1px solid #0f172a;height:48px}@media print{body{background:white;padding:0}.doc{box-shadow:none;border-radius:0}}`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char] ?? char));
}
